"""Read-side inventory of tenant configuration.

There is no usable server-side search — calculated fields have no filter
criteria at all, and report search is exact-match — so discovery means building
a local index and searching that. See `inventory.py` for the details.
"""

from wdmigrator.discovery.inventory import (
    DASHBOARD_FLAVOURS,
    IMPLEMENTER_REQUIRED_REMEDY,
    PAGE_SIZE,
    CalculatedFieldSummary,
    DashboardSummary,
    Index,
    IndexProgress,
    LookupOutcome,
    LookupResult,
    PromptSetSummary,
    ReportSummary,
    build_index,
    cache_path,
    classify_fault,
    find_report_by_exact_name,
    ids_of,
    iter_calculated_field_index,
    iter_dashboard_index,
    iter_prompt_set_index,
    iter_report_index,
    load_index,
    lookup_calculated_field,
    lookup_calculated_measure,
    lookup_dashboard,
    lookup_prompt_set,
    lookup_report,
    lookup_report_by_name,
    requires_implementer,
    save_index,
)

__all__ = [
    "DASHBOARD_FLAVOURS",
    "IMPLEMENTER_REQUIRED_REMEDY",
    "PAGE_SIZE",
    "CalculatedFieldSummary",
    "DashboardSummary",
    "Index",
    "IndexProgress",
    "LookupOutcome",
    "LookupResult",
    "PromptSetSummary",
    "ReportSummary",
    "build_index",
    "cache_path",
    "classify_fault",
    "find_report_by_exact_name",
    "ids_of",
    "iter_calculated_field_index",
    "iter_dashboard_index",
    "iter_prompt_set_index",
    "iter_report_index",
    "load_index",
    "lookup_calculated_field",
    "lookup_calculated_measure",
    "lookup_dashboard",
    "lookup_prompt_set",
    "lookup_report",
    "lookup_report_by_name",
    "requires_implementer",
    "save_index",
]
